In [56]:
import torch
import numpy as np
from pytorch3d.io import load_obj

if torch.cuda.is_available():
    device = torch.device("cuda:0")
    torch.cuda.set_device(device)
else:
    device = torch.device("cpu")

In [57]:
#obj_filename = "data/subaru/_Subaru-Loyale.obj"
#obj_filename = "data/cow_mesh/cow.obj"
obj_filename = "data/Jeep_Renegade_2016_obj/Jeep_Renegade_2016.obj"

verts, faces, aux = load_obj(
    obj_filename,
    device=device,
    load_textures=True,
    create_texture_atlas=True,
    texture_atlas_size=4,
    texture_wrap="repeat"
     )

verts=verts.numpy()

In [58]:
print(verts)

[[-2.16573e-15  1.75011e+00 -1.56400e+00]
 [-1.80478e-15  1.91707e+00 -1.63125e+00]
 [-5.92280e-03  1.74645e+00 -1.57319e+00]
 ...
 [-7.52819e-01  1.16518e+00  5.26561e-01]
 [-7.55260e-01  1.15527e+00  4.37650e-01]
 [-7.84192e-01  1.13348e+00  4.19312e-01]]


In [59]:
def ritter(points, k):
    # Initialize center and radius
    center = points[np.random.randint(len(points))]
    radius = 0

    # Iterate k times
    for i in range(k):
        # Find the farthest point from center
        dists = np.linalg.norm(points - center, axis=1)
        p = points[np.argmax(dists)]
        d = dists.max()

        # Update center and radius
        if d > radius:
            radius = (radius + d) / 2
            center = center + (d - radius) * (p - center) / d
    
    # Return center and radius
    return (center, radius)

# Call the function with verts as input
center, radius = ritter(verts, 10) # k = 10 iterations

# Print the output
print(f"Center: {center}")
print(f"Radius: {radius}")

Center: [-0.0625834   0.7186213  -0.05095521]
Radius: 2.191200494300574


In [55]:
def bounding_sphere_exact(points):
    """
    Computes the bounding sphere of a set of points in 3D space.
    
    Args:
    - points: a numpy array of shape (n, 3) representing the n points in 3D space
    
    Returns:
    - center: a numpy array of shape (3,) representing the center of the bounding sphere
    - radius: a float representing the radius of the bounding sphere
    """
    # Compute the center of mass
    center = np.mean(points, axis=0)
    
    # Compute the radius
    radius = np.max(np.linalg.norm(points - center, axis=1))
    
    return center, radius

center, radius = bounding_sphere(verts)
# Print the output
print(f"Center: {center}")
print(f"Radius: {radius}")

Center: [1.78877499e-08 1.02965936e-01 1.93355814e-01]
Radius: 1.0782541036605835
